### PR TITLE
Add dummy file for testing pull requests

### PR DESCRIPTION
**Pull request by nrotella**
I used my personal Github account to add a dummy file for testing pull requests on a fork of our (now-deprecated) public-facing radar ROS driver package.

### CODE REVIEW

**Comment by nrotella-ainstein** [comment]
Testing comments.

**Comment by nrotella-ainstein** [comment]
Here's another comment.

**Comment by nrotella-ainstein** [comment]
Closing, this file is only for testing and will not be merged.

**Comment by nrotella** [comment]
Ok.

**Pull request closed without merging**
